# .github/actions/publish-allure-to-pages/action.yml
name: "Publish Allure to Pages (non-overwrite)"
description: "Builds Allure HTML from results and publishes to a Pages branch under a unique subfolder, preserving history."
author: "you"

inputs:
  results_zip:
    description: "Path to zipped allure-results created earlier"
    required: true
  build_id:
    description: "Build ID used as folder name"
    required: true
  pages_branch:
    description: "Branch that GitHub Pages serves from (Settings → Pages)"
    required: false
    default: "allure-report"
  base_path:
    description: "Base folder on the Pages branch to store reports"
    required: false
    default: "reports"
  site_title:
    description: "Title for index.html (unused when no index is generated)"
    required: false
    default: "Allure Reports"
  folder_prefix:
    description: "Optional prefix for the folder (e.g., run-). Final path: base_path/<prefix><build_id>/"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Node (for Allure CLI via npm)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Allure CLI (npm)
      shell: bash
      run: |
        set -euo pipefail
        npm i -g allure-commandline
        echo "$(npm root -g)/allure-commandline/bin" >> "$GITHUB_PATH"
        echo "Allure version: $(allure --version)"

    - name: Unzip allure-results
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ./_work/allure-results
        unzip -q "${{ inputs.results_zip }}" -d ./_work/allure-results
        echo "Unzipped to _work/allure-results"
        ls -la ./_work/allure-results || true

    - name: Generate Allure HTML
      shell: bash
      run: |
        set -euo pipefail
        allure generate ./_work/allure-results -o ./_work/allure-report --clean
        test -f ./_work/allure-report/index.html

    - name: Publish to Pages branch (preserve history, no index.html)
      shell: bash
      env:
        BRANCH: ${{ inputs.pages_branch }}
        BASE:   ${{ inputs.base_path }}
        BID:    ${{ inputs.build_id }}
        PREFIX: ${{ inputs.folder_prefix }}
      run: |
        set -euo pipefail

        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Check if the branch exists on origin
        if git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
          git fetch origin "$BRANCH":"refs/remotes/origin/$BRANCH" --depth=1
          git checkout -B "$BRANCH" "origin/$BRANCH"
        else
          git checkout --orphan "$BRANCH"
          git rm -r --cached . >/dev/null 2>&1 || true
          find . -mindepth 1 -maxdepth 1 -not -name ".git" -exec rm -rf {} +
        fi

        mkdir -p "$BASE"
        DEST="$BASE/${PREFIX}${BID}"
        mkdir -p "$DEST"

        rsync -a --delete ./_work/allure-report/ "$DEST/"

        git add -A
        git commit -m "Publish Allure report for build ${BID} at ${DEST}" || echo "No changes to commit."
        git push origin "$BRANCH"
