name: "Publish Allure to Pages (non-overwrite)"
description: "Build Allure HTML from results and push to a Pages branch under a unique subfolder, preserving history."
author: "you"

inputs:
  results_zip:
    description: "Path to a ZIP of allure-results (relative to repo root or absolute)"
    required: true
  build_id:
    description: "Folder name to use on the Pages branch (e.g. a build/run id)"
    required: true
  pages_branch:
    description: "Branch that GitHub Pages serves from"
    required: false
    default: "allure-report"
  base_path:
    description: "Base folder on the Pages branch where reports live"
    required: false
    default: "reports"
  folder_prefix:
    description: "Optional folder prefix (e.g. run-). Final path: base_path/<prefix><build_id>/"
    required: false
    default: ""
  pages_base_url:
    description: "Optional absolute base URL for Pages, e.g. https://<org>.github.io/<repo>. If empty, the action will guess it."
    required: false
    default: ""

outputs:
  report_branch:
    description: "Branch the report was pushed to"
    value: ${{ steps.publish.outputs.report_branch }}
  report_path:
    description: "Path to the report folder on the Pages branch"
    value: ${{ steps.publish.outputs.report_path }}
  report_url:
    description: "Full URL to the report (index.html)"
    value: ${{ steps.publish.outputs.report_url }}

runs:
  using: "composite"
  steps:
    - name: Verify repo checkout
      shell: bash
      run: |
        set -euo pipefail
        test -d .git || { echo "This action requires actions/checkout to have run first."; exit 1; }

    - name: Set up Node (for Allure CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Allure CLI
      shell: bash
      run: |
        set -euo pipefail
        npm i -g allure-commandline
        echo "$(npm root -g)/allure-commandline/bin" >> "$GITHUB_PATH"
        allure --version || true

    - name: Unzip allure-results
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p _work/allure-results
        unzip -q "${{ inputs.results_zip }}" -d _work/allure-results
        test -d _work/allure-results

    - name: Generate Allure HTML
      shell: bash
      run: |
        set -euo pipefail
        allure generate _work/allure-results -o _work/allure-report --clean
        test -f _work/allure-report/index.html

    - name: Publish to Pages branch via worktree (preserve history)
      id: publish
      shell: bash
      env:
        BRANCH: ${{ inputs.pages_branch }}
        BASE:   ${{ inputs.base_path }}
        BID:    ${{ inputs.build_id }}
        PREFIX: ${{ inputs.folder_prefix }}
        PAGES_BASE_URL: ${{ inputs.pages_base_url }}
      run: |
        set -euo pipefail

        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        WT="_pages_worktree"
        rm -rf "$WT"

        # Fetch remote info about target branch (if it exists)
        git fetch --no-tags --depth=1 origin "+refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH}" || true

        if git show-ref --verify --quiet "refs/remotes/origin/${BRANCH}"; then
          git worktree add --force -B "$BRANCH" "$WT" "origin/${BRANCH}"
        else
          git worktree add --detach "$WT"
          (
            cd "$WT"
            git checkout --orphan "$BRANCH"
            find . -mindepth 1 -maxdepth 1 -not -name ".git" -exec rm -rf {} +
          )
        fi

        DEST="${BASE}/${PREFIX}${BID}"
        (
          cd "$WT"
          mkdir -p "$DEST"
          if command -v rsync >/dev/null 2>&1; then
            rsync -a --delete "../_work/allure-report/" "$DEST/"
          else
            rm -rf "$DEST"/*
            cp -a ../_work/allure-report/. "$DEST/"
          fi
          touch .nojekyll
          git add -A
          git commit -m "Publish Allure report for build ${BID} at ${DEST}" || echo "No changes to commit."
          git push -u origin "$BRANCH"
        )

        # Derive Pages base URL if not provided:
        # Default project pages assumption: https://<owner>.github.io/<repo>
        owner_repo="${GITHUB_REPOSITORY}"
        owner="${owner_repo%%/*}"
        repo="${owner_repo##*/}"
        if [ -z "${PAGES_BASE_URL}" ]; then
          PAGES_BASE_URL="https://${owner}.github.io/${repo}"
        fi

        REPORT_PATH="${DEST}"
        REPORT_URL="${PAGES_BASE_URL}/${REPORT_PATH}/index.html"

        # Expose as outputs
        {
          echo "report_branch=${BRANCH}"
          echo "report_path=${REPORT_PATH}"
          echo "report_url=${REPORT_URL}"
        } >> "$GITHUB_OUTPUT"

        # Also export a convenient env var for the rest of the job
        echo "ALLURE_REPORT_URL=${REPORT_URL}" >> "$GITHUB_ENV"

        # Cleanup worktree registration
        git worktree remove "$WT" --force || true
